name: Auto PR Main

on:
  push:
    branches:
      - develop

permissions:
  contents: write
  pull-requests: write

jobs:

  create-pr:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Create PR
        env:
          GH_TOKEN: ${{ secrets.MIRANTE_ACTIONS_PAT_SICOOB }}
        run: |

          gh pr create \
            --base main \
            --head develop \
            --title "Release" \
            --body "PR automático."
